### ISSUE TITLE
Chrome high CPU/GPU utilization

### ISSUE THREAD

**Issue by realEBongo** [cynicaloptimist/improved-initiative#460]
For some reason, whenever I open an II encounter in Chrome, my CPU now ramps up to about 30% and my GPU runs at about 8%.  I considered this no big deal, but it makes the fan in my small laptop scream, so it is kind of annoying.  I've used II for almost a year now and only noticed this issue about 2-3 weeks ago.  I figured it was a problem with my laptop, but in recent debug I discovered I have near 0% utilization increase when I use MS Edge instead of Chrome.  If there is more info I can provide to help debug, please let me know.

**Comment by realEBongo** [comment]
I downloaded Firefox, and confirmed no issues with it as well, fwiw.  Looks like a viable workaround for me for the foreseeable future.

**Comment by cynicaloptimist** [comment]
This is a hard one to diagnose, but it might be reproducible with a copy of your exported user data.

**Comment by realEBongo** [comment]
[improved-initiative ebongo 1-6-20.txt](https://github.com/cynicaloptimist/improved-initiative/files/4026574/improved-initiative.ebongo.1-6-20.txt)

Renamed my JSON to .txt.  Still reproducible as of this morning.  I've been using Firefox in the meantime without issue.

**Comment by realEBongo** [comment]
I was looking at the issue in the Chrome debugger this morning and I noticed a few things that might help narrow it down:

1. The issue seems to only appear with the "narrow" toolbar.  My II always starts in narrow mode.  When I toggle to wide, the utilization immediately goes down and stays down.  If I toggle back to narrow, the app freezes up (and the high utilization re-occurs).
2. After opening the library and starting a search, when I look closely, I can see the toolbar jittering slightly in the top half.  After turning on the debugger I can see that it is constantly resizing a certain div element between 58 and 59 pixels.
![image](https://user-images.githubusercontent.com/50776455/71827834-b2a24d80-3066-11ea-80d0-aa4783ae1aae.png). 

So... it seems there is a key relationship with the toolbar that I didn't previously notice.

**Comment by cynicaloptimist** [comment]
Sounds like I misconfigured the useEffect hook in [Toolbar.tsx:18](https://github.com/cynicaloptimist/improved-initiative/blob/aac266f86b34681afea1c3de0685e279de141e99/client/Commands/Toolbar.tsx#L18) maybe.

**Comment by realEBongo** [comment]
@cynicaloptimist - I regret that I'm still pretty nooby on code development, so I don't know how to test other than the released version.  Should I just wait for the next release to test?

**Comment by cynicaloptimist** [comment]
Yeah, I just made that comment as a note to myself or anyone else who picks up this issue. Not high priority yet since I can't reproduce it.

**Comment by cynicaloptimist** [comment]
I'll deploy a build this week that might fix the issue, or will at least help me troubleshoot.

**Comment by cynicaloptimist** [comment]
Can you still repro this? I deployed an update the other day that might remedy the issue.

**Comment by realEBongo** [comment]
@cynicaloptimist Unfortunately, the issue persists, with the same symptoms.

**Comment by cynicaloptimist** [comment]
Ok, I've got something else to try that I'll deploy this week. Still haven't been able to reproduce it locally.

**Comment by cynicaloptimist** [comment]
Ok, how about now?

**Comment by realEBongo** [comment]
It's fixed!  Huzzah!
